ALTER TABLE user
MODIFY COLUMN id INT AUTO_INCREMENT COMMENT '用户 ID（自增主键）',
MODIFY COLUMN username VARCHAR(255) COMMENT '用户名（可选）',
MODIFY COLUMN phone VARCHAR(255) COMMENT '手机号（可选）',
MODIFY COLUMN email VARCHAR(255) COMMENT '邮箱（可选）',
MODIFY COLUMN password VARCHAR(255) COMMENT '密码（加密存储）',
MODIFY COLUMN nickname VARCHAR(255) COMMENT '昵称',
MODIFY COLUMN avatar VARCHAR(255) COMMENT '头像 URL',
MODIFY COLUMN openId VARCHAR(255) COMMENT '微信 OpenID（小程序登录）',
MODIFY COLUMN unionId VARCHAR(255) COMMENT '微信 UnionID（跨平台用户识别）',
MODIFY COLUMN appleId VARCHAR(255) COMMENT 'Apple ID（苹果登录）',
MODIFY COLUMN googleId VARCHAR(255) COMMENT 'Google ID（谷歌登录）',
MODIFY COLUMN status VARCHAR(255) DEFAULT 'active' COMMENT '用户状态：active（激活）、disabled（禁用）',
MODIFY COLUMN createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
MODIFY COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
MODIFY COLUMN lastLoginAt DATETIME COMMENT '最后登录时间',
MODIFY COLUMN gender VARCHAR(255) COMMENT '性别：male（男）、female（女）、unknown（未知）',
MODIFY COLUMN birthday DATETIME COMMENT '生日',
MODIFY COLUMN address VARCHAR(255) COMMENT '地址';


ALTER TABLE image_record
MODIFY COLUMN imageUrl VARCHAR(255) COMMENT '图片 URL（必填）',
MODIFY COLUMN shotAt DATETIME COMMENT '图片拍摄时间（可选）',
MODIFY COLUMN latitude FLOAT COMMENT '图片拍摄纬度（可选）',
MODIFY COLUMN longitude FLOAT COMMENT '图片拍摄经度（可选）',
MODIFY COLUMN address VARCHAR(255) COMMENT '图片拍摄地址（可选）',
MODIFY COLUMN createdAt DATETIME COMMENT '记录创建时间（自动生成）',
MODIFY COLUMN updatedAt DATETIME COMMENT '记录更新时间（自动更新）',
MODIFY COLUMN description TEXT COMMENT '图片描述（可选）',
MODIFY COLUMN userId INT COMMENT '关联的用户 ID（可选）',
MODIFY COLUMN result JSON COMMENT '图片解析结果（JSON 格式，可选）';
